/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WebDialog {
        "close": () => Promise<void>;
        "header": string;
        "hideFooter": boolean;
        "maskClosable": boolean;
        "open": () => Promise<void>;
        "show": boolean;
        "showMask": boolean;
        "width": string;
    }
}
declare global {
    interface HTMLWebDialogElement extends Components.WebDialog, HTMLStencilElement {
    }
    var HTMLWebDialogElement: {
        prototype: HTMLWebDialogElement;
        new (): HTMLWebDialogElement;
    };
    interface HTMLElementTagNameMap {
        "web-dialog": HTMLWebDialogElement;
    }
}
declare namespace LocalJSX {
    interface WebDialog {
        "header"?: string;
        "hideFooter"?: boolean;
        "maskClosable"?: boolean;
        "show"?: boolean;
        "showMask"?: boolean;
        "width"?: string;
    }
    interface IntrinsicElements {
        "web-dialog": WebDialog;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "web-dialog": LocalJSX.WebDialog & JSXBase.HTMLAttributes<HTMLWebDialogElement>;
        }
    }
}
